# Generated by Django 5.2.12 on 2026-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "jira_comment_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Kommentar",
                "verbose_name_plural": "Kommentare",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("epic", "Epic"),
                            ("story", "Story"),
                            ("task", "Aufgabe"),
                            ("bug", "Bug"),
                            ("subtask", "Unteraufgabe"),
                        ],
                        default="task",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="to_do", max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("highest", "Höchste"),
                            ("high", "Hoch"),
                            ("medium", "Mittel"),
                            ("low", "Niedrig"),
                            ("lowest", "Niedrigste"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("story_points", models.IntegerField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "jira_issue_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "jira_issue_key",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("jira_updated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
            ],
            options={
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("archived", "Archiviert"),
                            ("paused", "Pausiert"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(
                        default=False, help_text="Wird mit Jira synchronisiert"
                    ),
                ),
                (
                    "jira_project_key",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "jira_project_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekte",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("goal", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Geplant"),
                            ("active", "Aktiv"),
                            ("closed", "Abgeschlossen"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "jira_sprint_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "ordering": ["-start_date"],
            },
        ),
    ]
