# Generated by Django 5.1.15 on 2026-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_add_git_repo_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="github_issue_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="github_issue_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="github_repo_full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="github_repo_full_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manuell"), ("jira", "Jira"), ("github", "GitHub")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
