# Generated by Django 5.2.12 on 2026-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_add_github_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="github_comment_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="github_assignee_login",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sprint",
            name="github_milestone_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
