# Generated by Django 5.2.12 on 2026-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titel")),
                ("message", models.TextField(verbose_name="Nachricht")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("deadline_warning", "Fristwarnung"),
                            ("sync_error", "Synchronisierungsfehler"),
                            ("ai_suggestion", "KI-Vorschlag"),
                            ("status_change", "Statusänderung"),
                            ("general", "Allgemein"),
                        ],
                        max_length=20,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warnung"),
                            ("urgent", "Dringend"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Schweregrad",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Gelesen")),
                (
                    "action_url",
                    models.CharField(blank=True, max_length=500, verbose_name="Aktions-URL"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadaten"),
                ),
            ],
            options={
                "verbose_name": "Benachrichtigung",
                "verbose_name_plural": "Benachrichtigungen",
                "ordering": ["-created_at"],
            },
        ),
    ]
