# Generated by Django 5.1.15 on 2026-03-25 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_add_github_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCompanyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Agentic Company", max_length=100)),
                (
                    "base_url",
                    models.CharField(
                        help_text="API-Basis-URL des Agent-Service", max_length=500
                    ),
                ),
                ("api_key", models.CharField(max_length=255)),
                (
                    "webhook_secret",
                    models.CharField(
                        help_text="HMAC-Secret für Webhook-Verifizierung",
                        max_length=255,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Company",
                "verbose_name_plural": "Agent Companies",
                "unique_together": {("user", "base_url")},
            },
        ),
        migrations.CreateModel(
            name="AgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ceo", "CEO"),
                            ("department_head", "Abteilungsleiter"),
                            ("specialist", "Spezialist"),
                            ("qa", "Qualitätssicherung"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("avatar_color", models.CharField(default="#6366F1", max_length=7)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("ai_provider", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Verfügbar"),
                            ("working", "Arbeitet"),
                            ("waiting", "Wartet"),
                            ("offline", "Offline"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="agents.agentcompanyconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["role", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_task_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Wartend"),
                            ("assigned", "Zugewiesen"),
                            ("in_progress", "In Bearbeitung"),
                            ("review", "Review"),
                            ("needs_input", "Rückfrage"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=3)),
                ("task_type", models.CharField(blank=True, max_length=50)),
                ("result_summary", models.TextField(blank=True)),
                ("deliverables", models.JSONField(blank=True, default=list)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="agents.agentprofile",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="agents.agentcompanyconfig",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tasks",
                        to="projects.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Task",
                "verbose_name_plural": "Agent Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("decision", "Entscheidung"),
                            ("question", "Rückfrage"),
                            ("handoff", "Übergabe"),
                            ("status_change", "Statusänderung"),
                            ("deliverable", "Ergebnis"),
                            ("error", "Fehler"),
                            ("system", "System"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_decision_pending", models.BooleanField(default=False)),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="agents.agentmessage",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="agents.agentprofile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agents.agenttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Message",
                "verbose_name_plural": "Agent Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
