# Generated by Django 5.1.15 on 2026-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('orchestrator', 'Orchestrator'), ('department_head', 'Abteilungsleiter'), ('coder', 'Entwickler'), ('writer', 'Redakteur'), ('researcher', 'Rechercheur'), ('specialist', 'Spezialist'), ('qa', 'Qualitätssicherung')], max_length=20),
        ),
    ]
