# Generated by Django 5.2.12 on 2026-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("summary", "Zusammenfassung"),
                            ("action_items", "Aktionspunkte"),
                            ("prioritization", "Priorisierung"),
                            ("daily_plan", "Tagesplan"),
                            ("extraction", "Extraktion"),
                            ("repo_analysis", "Repository-Analyse"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("input_preview", models.TextField(blank=True)),
                ("result", models.JSONField()),
                ("model_used", models.CharField(max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "KI-Ergebnis",
                "verbose_name_plural": "KI-Ergebnisse",
            },
        ),
    ]
