# Generated by Django 5.2.12 on 2026-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_reasoning", models.TextField(blank=True)),
                (
                    "capacity_hours",
                    models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Tagesplan",
                "verbose_name_plural": "Tagespläne",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField()),
                ("scheduled_start", models.TimeField(blank=True, null=True)),
                ("time_block_minutes", models.IntegerField(blank=True, null=True)),
                ("ai_reasoning", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tagesplan-Eintrag",
                "verbose_name_plural": "Tagesplan-Einträge",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PersonalTodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Dringend"),
                            (2, "Hoch"),
                            (3, "Mittel"),
                            (4, "Niedrig"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("in_progress", "In Bearbeitung"),
                            ("done", "Erledigt"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manuell"),
                            ("jira", "Jira"),
                            ("confluence", "Confluence"),
                            ("email", "E-Mail"),
                            ("teams", "Teams"),
                            ("ai", "KI"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "linked_confluence_page_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "linked_email_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Aufgabe",
                "verbose_name_plural": "Aufgaben",
                "ordering": ["-priority", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Wochenplan",
                "verbose_name_plural": "Wochenpläne",
                "ordering": ["-week_start"],
            },
        ),
    ]
