# Generated by Django 5.2.12 on 2026-03-23 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_add_git_repo_analysis"),
        ("todos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="daily_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="todos.dailyplan",
            ),
        ),
        migrations.AddField(
            model_name="personaltodo",
            name="linked_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personal_todos",
                to="projects.issue",
            ),
        ),
        migrations.AddField(
            model_name="personaltodo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personal_todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="todo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_items",
                to="todos.personaltodo",
            ),
        ),
        migrations.AddField(
            model_name="weeklyplan",
            name="daily_plans",
            field=models.ManyToManyField(blank=True, related_name="weekly_plans", to="todos.dailyplan"),
        ),
        migrations.AddField(
            model_name="weeklyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="dailyplanitem",
            unique_together={("daily_plan", "todo")},
        ),
        migrations.AlterUniqueTogether(
            name="weeklyplan",
            unique_together={("user", "week_start")},
        ),
    ]
