# Generated by Django 5.2.12 on 2026-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("attendees", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Kalender-Termin",
                "verbose_name_plural": "Kalender-Termine",
            },
        ),
        migrations.CreateModel(
            name="ConfluencePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confluence_page_id", models.CharField(max_length=50, unique=True)),
                ("space_key", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("content_text", models.TextField(blank=True)),
                ("last_confluence_update", models.DateTimeField()),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_action_items", models.JSONField(default=list)),
                ("ai_decisions", models.JSONField(default=list)),
                ("ai_risks", models.JSONField(default=list)),
                ("ai_processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Confluence-Seite",
                "verbose_name_plural": "Confluence-Seiten",
            },
        ),
        migrations.CreateModel(
            name="GitActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("commit", "Commit"),
                            ("pr_opened", "PR geöffnet"),
                            ("pr_merged", "PR gemerged"),
                            ("pr_closed", "PR geschlossen"),
                        ],
                        max_length=15,
                    ),
                ),
                ("author", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("external_id", models.CharField(max_length=255)),
                ("event_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Git-Aktivität",
                "verbose_name_plural": "Git-Aktivitäten",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="GitRepoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repo_full_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("primary_language", models.CharField(blank=True, max_length=100)),
                ("languages", models.JSONField(default=dict)),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("open_issues_count", models.IntegerField(default=0)),
                ("topics", models.JSONField(default=list)),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("readme_content", models.TextField(blank=True)),
                ("recent_commits_summary", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_tech_stack", models.JSONField(default=list)),
                ("ai_strengths", models.JSONField(default=list)),
                ("ai_improvements", models.JSONField(default=list)),
                ("ai_action_items", models.JSONField(default=list)),
                ("ai_processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Repository-Analyse",
                "verbose_name_plural": "Repository-Analysen",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("jira", "Jira"),
                            ("confluence", "Confluence"),
                            ("microsoft_calendar", "Microsoft Kalender"),
                            ("microsoft_email", "Microsoft E-Mail"),
                            ("microsoft_teams", "Microsoft Teams"),
                            ("microsoft_todo", "Microsoft To Do"),
                            ("github", "GitHub"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.JSONField(
                        default=dict, help_text="Verschlüsselte Zugangsdaten"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict, help_text="poll_interval, selected_projects etc."
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("idle", "Bereit"),
                            ("syncing", "Synchronisiert"),
                            ("error", "Fehler"),
                        ],
                        default="idle",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrationen",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Eingehend"),
                            ("outbound", "Ausgehend"),
                            ("bidirectional", "Bidirektional"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Gestartet"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        max_length=10,
                    ),
                ),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Sync-Protokoll",
                "verbose_name_plural": "Sync-Protokolle",
                "ordering": ["-started_at"],
            },
        ),
    ]
