# Generated by Django 5.2.12 on 2026-03-23 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_add_git_repo_analysis"),
        ("projects", "0001_add_git_repo_analysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gitactivity",
            name="linked_issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="git_activities",
                to="projects.issue",
            ),
        ),
        migrations.AddField(
            model_name="gitactivity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="git_activities",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="integrationconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to="integrations.integrationconfig",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integrationconfig",
            unique_together={("user", "integration_type")},
        ),
    ]
