# Generated by Django 5.2.12 on 2026-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_add_git_repo_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("commit", "Commit"),
                    ("pr_opened", "PR geöffnet"),
                    ("pr_merged", "PR gemerged"),
                    ("pr_closed", "PR geschlossen"),
                    ("pr_reviewed", "PR reviewt"),
                ],
                max_length=20,
            ),
        ),
    ]
